version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      non-major:
        update-types:
          - minor
          - patch